PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dsv: <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sh: <http://purl.org/skos-history/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
#
# identify concepts inserted with a certain version, and show their top concepts
#
SELECT ?topConcept (str(?topLabel) AS ?topConceptLabel) (?concept AS ?addedConcept) (str(?prefLabel) AS ?addedConceptLabel)
WHERE {
  # parameters
  VALUES ( ?versionHistoryGraph ?language ) {
    ( <http://zbw.eu/stw/version> "en" )
  }
  GRAPH ?versionHistoryGraph {
    # use current version as default
    ?versionset dsv:currentVersionRecord ?currentVHR .
    ?currentVHR sh:hasDelta ?delta .
    ?currentVHR sh:usingNamedGraph/sd:name ?versionGraph .
    # get the delta to the previous version
    ?currentVHR xhv:prev ?previousVHR .
    ?delta sh:deltaTo ?currentVHR .
    ?delta sh:deltaFrom ?previousVHR .
    # identify insertions and deletions parts/graphs
    ?delta dcterms:hasPart ?insertions .
    ?insertions a sh:SchemeDeltaInsertions .
    ?insertions sh:usingNamedGraph/sd:name ?insertionsGraph .
    ?delta dcterms:hasPart ?deletions .
    ?deletions a sh:SchemeDeltaDeletions .
    ?deletions sh:usingNamedGraph/sd:name ?deletionsGraph .
  }
  # for each inserted concept, a (newly inserted) prefLabel must exist ...
  GRAPH ?insertionsGraph {
    ?concept skos:prefLabel ?prefLabel
  }
  # ... without any prefLabel deleted for this concept
  FILTER NOT EXISTS {
    GRAPH ?deletionsGraph {
      ?concept skos:prefLabel []
    }
  }
  GRAPH ?versionGraph {
    # get the top concept(s) (which, for STW, always are defined
    # as a subsection of the thesaurus and where a concept may have
    # multiple top concepts)
    ?concept skos:broader+ ?topConcept .
    ?scheme skos:hasTopConcept ?topConcept .
    ?topConcept skos:prefLabel ?topLabel .
  }
  # restrict output to a certain language
  FILTER (lang(?prefLabel) = ?language && lang(?topLabel) = ?language)
}
ORDER BY ?topLabel ?prefLabel
