PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  delta: <http://www.w3.org/2004/delta#>
PREFIX  dsv:  <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  sd:   <http://www.w3.org/ns/sparql-service-description#>
PREFIX  sh:   <http://raw.github.com/jneubert/skos-history/master/skos-history.ttl/>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  xhv:  <http://www.w3.org/1999/xhtml/vocab#>

# version deltas for a single concept

# TODO: remove empty blank nodes (see
# http://answers.semanticweb.com/questions/20908/sparql-construct-without-distinct-produces-non-lean-output)

CONSTRUCT {
  ?concept sh:history ?conceptDelta .
  ?conceptDelta
    delta:deletion [ ?predicate ?deletion ] ;
    delta:insertion [ ?predicate ?insertion ] .
}

WHERE {
  {
    GRAPH ?versionHistoryGraph
      {
        # use subquery to filter out duplicates
        SELECT DISTINCT ?concept ?conceptDelta ?predicate ?deletion ?insertion
        WHERE
        {
          ?vhr a dsv:VersionHistoryRecord .#
          ?vhr sh:hasDelta ?delta .
          ?delta dcterms:hasPart ?part .

          # identify insertions and deletions parts/graphs
          ?delta dcterms:hasPart ?insertions .
          ?insertions rdf:type sh:SchemeDeltaInsertions .
          ?insertions sh:usingNamedGraph/sd:name ?insertionsGraph .
          ?delta dcterms:hasPart ?deletions .
          ?deletions rdf:type sh:SchemeDeltaDeletions .
          ?deletions sh:usingNamedGraph/sd:name ?deletionsGraph .


          # for each version, work on insertions and deletions part
            {
              GRAPH ?deletionsGraph {
                ?concept ?predicate ?deletion .
              }
            }
          UNION
            {
              GRAPH ?insertionsGraph {
                ?concept ?predicate ?insertion .
              }
            }

        # for the clarity of the example, filter out some dataset-wide changes in STW
        FILTER ( ?predicate NOT IN (<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, <http://purl.org/ontology/gbv/gvkppn>) )

        # build a uri to group the changes for a particular version
        BIND (uri(concat(str(?concept), strafter(str(?delta), "/stw"))) AS ?conceptDelta)
      }
    }
  }
}

# parameters
VALUES ( ?versionHistoryGraph ?concept ) { ( <http://zbw.eu/stw/version> <http://zbw.eu/stw/descriptor/12571-4> ) }

