PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dsv: <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sh: <http://raw.github.com/jneubert/skos-history/master/skos-history.ttl/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
#
# Count deleted labels in a certain language per version
#
SELECT ?version (str(count(distinct ?label)) as ?deletedLabelCount)
WHERE {
  # parameters
  VALUES ( ?versionHistoryGraph ?language) {
    ( <http://zbw.eu/stw/version> "en" )
  }
  GRAPH ?versionHistoryGraph {
    ?delta a sh:SchemeDelta .
    ?delta sh:deltaTo/dc:identifier ?version .
    # identify insertions and deletions parts/graphs
    ?delta dcterms:hasPart ?insertions .
    ?insertions a sh:SchemeDeltaInsertions .
    ?insertions sh:usingNamedGraph/sd:name ?insertionsGraph .
    ?delta dcterms:hasPart ?deletions .
    ?deletions a sh:SchemeDeltaDeletions .
    ?deletions sh:usingNamedGraph/sd:name ?deletionsGraph .
  }
  # for each deleted concept, a deleted prefLabel must exist ...
  GRAPH ?deletionsGraph {
    [] skos:prefLabel | skos:altLabel ?label
  }
  # ... without anything remaining for this concept in the current version
  FILTER NOT EXISTS {
    GRAPH ?insertionsGraph {
      [] skos:prefLabel | skos:altLabel ?label
    }
  }
  FILTER (lang(?label) = ?language)
}
GROUP BY ?version
ORDER BY ?version
