PREFIX  dsv:  <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX  sd:   <http://www.w3.org/ns/sparql-service-description#>
PREFIX  sh:   <http://raw.github.com/jneubert/skos-history/master/skos-history.ttl/>

# get the graph name of the current version

SELECT  ?currentVersion
WHERE
  { GRAPH ?versionHistoryGraph
      { ?versionset (dsv:currentVersionRecord/sh:usingNamedGraph)/sd:name ?currentVersion }
  }

# parameters
VALUES ?versionHistoryGraph { <http://zbw.eu/stw/version> }

