PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dsv:     <https://raw.github.com/JohanDS/Dataset-versioning--for-KOS-data-sets-/master/DataSetVersioning.owl#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>

# get the current version graph name

SELECT  ?currentVersion
WHERE
  { 
    GRAPH <http://zbw.eu/stw/version>
      { ?versionset dsv:currentVersionRecord ?currentVersion }
  }
