PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh:      <http://raw.github.com/jneubert/skos-history/master/skos-history.ttl/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX text:    <http://jena.apache.org/text#>

# identify concepts inserted with a certain version

select ?s ?prefLabel
where {
  bind (<http://zbw.eu/stw/version/8.10> as $version)
  graph $version {
    ?delta sh:deltaTo ?version .
    ?delta dcterms:hasPart ?insertions .
    ?insertions a sh:SchemeDeltaInsertions .
    ?delta dcterms:hasPart ?deletions .
    ?deletions a sh:SchemeDeltaDeletions .
    graph ?insertions { 
      ?s skos:prefLabel ?prefLabel .
    }
    filter not exists { 
      graph ?deletions {
        ?s skos:prefLabel []
      }
    }
  }
}
order by $s
