# Discover the version history graph and all available scheme versions
#
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dsv: <http://purl.org/iso25964/DataSet/Versioning#>
#
SELECT ?versionHistoryGraph (?vhr AS ?versionHistoryRecord) (?identifier AS ?version) (str(?vhrDate) AS ?date) ?current
WHERE {
  GRAPH ?versionHistoryGraph {
    ?vhr dsv:hasVersionHistorySet ?vhs .
    ?vhr dc:date ?vhrDate .
    ?vhr dc:identifier ?identifier
    OPTIONAL {
      ?vhs dsv:currentVersionRecord ?current
      FILTER ( ?vhr = ?current )
    }
  }
}
ORDER BY ?date
