PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dsv: <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sh: <http://purl.org/skos-history/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
# show all labels deleted in the current version
#
SELECT  (str(?label) AS ?deletedLabel) ?previousConcept (str(?prefLabel) AS ?previousConceptLabel)
WHERE {
  # parameters
  VALUES ( ?versionHistoryGraph ?type ?language ) {
    ( <http://zbw.eu/stw/version> "Descriptor" "de" )
  }
  GRAPH ?versionHistoryGraph {
    # the compared versions default to the current and the previous one
    ?versionset dsv:currentVersionRecord/xhv:prev/dc:identifier ?oldVersion .
    ?versionset dsv:currentVersionRecord/dc:identifier ?newVersion .
    # get the delta and via that the relevant graphs
    ?delta a sh:SchemeDelta ;
      sh:deltaFrom/dc:identifier ?oldVersion ;
      sh:deltaTo/dc:identifier ?newVersion ;
      sh:deltaFrom/sh:usingNamedGraph/sd:name ?oldVersionGraph ;
      dcterms:hasPart ?insertions ;
      dcterms:hasPart ?deletions .
    ?insertions a sh:SchemeDeltaInsertions ;
      sh:usingNamedGraph/sd:name ?insertionsGraph .
    ?deletions a sh:SchemeDeltaDeletions ;
      sh:usingNamedGraph/sd:name ?deletionsGraph .
  }
  # get all deleted labels
  GRAPH ?deletionsGraph {
    [] skos:prefLabel | skos:altLabel ?label 
  }
  # ... which were not attached to some (other) concept now
  FILTER NOT EXISTS {
    GRAPH ?insertionsGraph {
      [] skos:prefLabel | skos:altLabel ?label 
    }
  }
  FILTER (lang(?label) = ?language)
  GRAPH ?oldVersionGraph {
    # get concepts and restrict to descriptors
    ?previousConcept skos:prefLabel | skos:altLabel ?label ;
      skos:prefLabel ?prefLabel .
    # STW 8.04 used a different custom namespace URI
    BIND (uri(concat("http://zbw.eu/namespaces/skos-extensions/", ?type)) as ?oldConceptType)
    BIND (uri(concat("http://zbw.eu/namespaces/zbw-extensions/", ?type)) as ?conceptType)
    {
      ?previousConcept a ?oldConceptType 
    } UNION {
      ?previousConcept a ?conceptType
    }
  }
  # restrict output to a certain language
  FILTER (lang(?prefLabel) = ?language)
}
ORDER BY ?label
