PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dsv: <http://purl.org/iso25964/DataSet/Versioning#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sh: <http://purl.org/skos-history/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
# show all labels added in the current version
#
SELECT  (str(?label) AS ?movedLabel) ?oldLabelType ?oldConcept (str(?oldPrefLabel) as ?oldConceptLabel)
?newLabelType ?newConcept (str(?newPrefLabel) as ?newConceptLabel)
WHERE {
  # parameters
  VALUES ( ?versionHistoryGraph ?conceptType ?language ) {
    ( <http://zbw.eu/stw/version> zbwext:Descriptor "en" )
  }
  GRAPH ?versionHistoryGraph {
    # the compared versions default to the current and the previous one
    ?versionset dsv:currentVersionRecord/xhv:prev/dc:identifier ?oldVersion .
    ?versionset dsv:currentVersionRecord/dc:identifier ?newVersion .
    # get the delta and via that the relevant graphs
    ?delta a sh:SchemeDelta ;
      sh:deltaFrom/dc:identifier ?oldVersion ;
      sh:deltaTo/dc:identifier ?newVersion ;
      sh:deltaFrom/sh:usingNamedGraph/sd:name ?oldVersionGraph ;
      sh:deltaTo/sh:usingNamedGraph/sd:name ?newVersionGraph ;
      dcterms:hasPart ?insertions ;
      dcterms:hasPart ?deletions .
    ?insertions a sh:SchemeDeltaInsertions ;
      sh:usingNamedGraph/sd:name ?insertionsGraph .
    ?deletions a sh:SchemeDeltaDeletions ;
      sh:usingNamedGraph/sd:name ?deletionsGraph .
  }
  # get deleted labels (in all languages) ...
  GRAPH ?deletionsGraph {
    ?oldConcept skos:prefLabel | skos:altLabel ?label .
    ?oldConcept ?oldLabelType ?label .
  }
  # ... which have been moved to another concept (or perhaps have got another labelType)
  GRAPH ?insertionsGraph {
    ?newConcept skos:prefLabel | skos:altLabel ?label .
    ?newConcept ?newLabelType ?label .
  }
  # restrict to a certain concept type and get additional information
  GRAPH ?oldVersionGraph {
    ?oldConcept skos:prefLabel | skos:altLabel ?label .
    ?oldConcept a ?conceptType .
    ?oldConcept skos:prefLabel ?oldPrefLabel .
  }
  FILTER (lang(?oldPrefLabel) = ?language)
  GRAPH ?newVersionGraph {
    ?newConcept skos:prefLabel | skos:altLabel ?label .
    ?newConcept a ?conceptType .
    ?newConcept skos:prefLabel ?newPrefLabel .
    #    OPTIONAL {
    #      ?oldConcept owl:deprecated ?deprecated
    #    } .
  }
  FILTER (lang(?newPrefLabel) = ?language)
}
ORDER BY ?oldPrefLabel ?label
